
package Interface;

import Interface_test.*;


public class UserPane extends javax.swing.JPanel {


    public UserPane() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioColor = new javax.swing.JRadioButton();
        Radio_Texture = new javax.swing.JRadioButton();
        Radio_Shape = new javax.swing.JRadioButton();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RadioColor.setText("Color");
        add(RadioColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        Radio_Texture.setText("Texture");
        add(Radio_Texture, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        Radio_Shape.setText("Shape");
        add(Radio_Shape, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, 50));
        add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 210, -1));
        add(jSlider3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioColor;
    private javax.swing.JRadioButton Radio_Shape;
    private javax.swing.JRadioButton Radio_Texture;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    // End of variables declaration//GEN-END:variables

}
