
package Interface_test;

// ********************************* Uncomment below *********************************//
//public class UserPane extends javax.swing.JPanel {


    public UserPane() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Radio_Color = new javax.swing.JRadioButton();
        Radio_Texture = new javax.swing.JRadioButton();
        Radio_Shape = new javax.swing.JRadioButton();
        colorslider = new javax.swing.JSlider();
        textureslider = new javax.swing.JSlider();
        shapeslider = new javax.swing.JSlider();
        Button_Search = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Radio_Color.setText("Color");
        add(Radio_Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Radio_Texture.setText("Texture");
        add(Radio_Texture, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        Radio_Shape.setText("Shape");
        add(Radio_Shape, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        add(colorslider, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 50));
        add(textureslider, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 210, -1));
        add(shapeslider, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, -1));

        Button_Search.setText("Search");
        Button_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SearchActionPerformed(evt);
            }
        });
        add(Button_Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Button_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SearchActionPerformed
        // TODO add your handling code here:
        // Perform Action**************************************************//***********************
    }//GEN-LAST:event_Button_SearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Search;
    private javax.swing.JRadioButton Radio_Color;
    private javax.swing.JRadioButton Radio_Shape;
    private javax.swing.JRadioButton Radio_Texture;
    private javax.swing.JSlider colorslider;
    private javax.swing.JSlider shapeslider;
    private javax.swing.JSlider textureslider;
    // End of variables declaration//GEN-END:variables



    public int getcolorvalue(){
    
        if(Radio_Color.isSelected())
            return (colorslider.getValue());
        else return 0;
    }

    public int gettexturervalue(){

        if(Radio_Texture.isSelected())
            return (textureslider.getValue());
        else return 0;
    }

    public int getshapevalue(){

        if(Radio_Shape.isSelected())
            return (shapeslider.getValue());
        else return 0;
    }
}

